language: r

warnings_are_errors: true

apt_packages:
  - libssl-dev
  - libapparmor-dev
  - libprotobuf-dev
  - libprotoc-dev
  - protobuf-compiler

notifications:
  email:
    on_success: change
    on_failure: change
